"""Initial migration

Revision ID: 0fec946674b9
Revises: 
Create Date: 2025-08-19 22:02:15.963245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fec946674b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('spotify_url', sa.String(length=500), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('external_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_index(op.f('ix_artists_spotify_id'), 'artists', ['spotify_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=255), nullable=False),
    sa.Column('spotify_access_token', sa.Text(), nullable=True),
    sa.Column('spotify_refresh_token', sa.Text(), nullable=True),
    sa.Column('spotify_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_spotify_user_id'), 'users', ['spotify_user_id'], unique=True)
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('release_type', sa.String(length=50), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_tracks', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('spotify_url', sa.String(length=500), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('external_urls', sa.JSON(), nullable=True),
    sa.Column('is_new_release', sa.Boolean(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_artist_id'), 'releases', ['artist_id'], unique=False)
    op.create_index(op.f('ix_releases_id'), 'releases', ['id'], unique=False)
    op.create_index(op.f('ix_releases_name'), 'releases', ['name'], unique=False)
    op.create_index(op.f('ix_releases_spotify_id'), 'releases', ['spotify_id'], unique=True)
    op.create_table('user_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('listening_rank', sa.Integer(), nullable=True),
    sa.Column('play_count_estimate', sa.Float(), nullable=True),
    sa.Column('discovered_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_enabled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_artists_artist_id'), 'user_artists', ['artist_id'], unique=False)
    op.create_index(op.f('ix_user_artists_id'), 'user_artists', ['id'], unique=False)
    op.create_index(op.f('ix_user_artists_user_id'), 'user_artists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_artists_user_id'), table_name='user_artists')
    op.drop_index(op.f('ix_user_artists_id'), table_name='user_artists')
    op.drop_index(op.f('ix_user_artists_artist_id'), table_name='user_artists')
    op.drop_table('user_artists')
    op.drop_index(op.f('ix_releases_spotify_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_name'), table_name='releases')
    op.drop_index(op.f('ix_releases_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_artist_id'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_users_spotify_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_artists_spotify_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
